server:
  port: 8088
spring:
  datasource:
    first:
      jdbc-url: jdbc:mysql://192.168.10.10:3306/qkhc_tj?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: qiankun2019.*
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost:1434;DatabaseName=db1
      username: sa
      password: mxy68128
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  thymeleaf:
    suffix: .html
    cache: false
    #设置为传统模式，防止因为严格的语法检测遇到的各种麻烦，例如<html />后习惯不会去加斜杠就会被当做错误检测
    mode: LEGACYHTML5



